Add updated teapot 09/24

diff --git a/teapot b/teapot
--- a/teapot
+++ b/teapot
@@ -1,16 +1,44 @@
-#!/bin/bash
+#!/bin/sh
 
-#TODO - replace *.mp3 *.wav etc with EXTENSIONS variable
+#==== FIXES ====
 #TODO - port to linux (afinfo)
 #TODO - if possible, pause
-#TODO - make .config, replace $MUSIC_DIR with user's default for good
-#TODO - go back to browse songs again after clicking q in less
-#TODO - fix youtube-dl failing but printing successful output (maybe just remove that message)
-#TODO - update array after downloading new song 
-#TODO - allow user to (r)efresh (ascii animation of water being drank), recreate array
-	#OR after every update refresh array (expensive)
+#TODO - make ./config, replace $MUSIC_DIR with user's default for good
+	#or do it with curl somehow
+#TODO - fix bug with delete not working when asking for index
+#TODO - fix l coming up in index
+#TODO - fix download press any key to quit
+#TODO - find strange bug with n not working sometimes
+#TODO - catch ctrl z
+
+
+#==== FEATURES ====
 #TODO - add (r)ename option (enter new name: mv $MUSIC_DIR/MUSIC_LIST(SONG_INDEX $MUSIC_DIR/new name)
 #TODO - loop feature (dont update SONGINDEX)
+	#display unloop_options (unloop, quit)
+#TODO - get_duration function (possibly show duration on main screen, update it in loop - SECONDS)
+#TODO - consider putting caffeinate in setup 
+#TODO - add h for help/or tutorial
+#TODO - Use recursive search and find all music files on computer -> music_list
+	# Should be an option not default behavior, probably intensive
+#TODO - add minigames to mp3 player
+	#(1) "rate songs", at the end it displays your favorite song and the ratings you gave
+	#(2) somehow find tempo of song and display animation correspondingly (using $SECONDS)
+	#(3) random animation
+	# eesh, no bloat pls
+#TODO - show metadata option (afinfo)
+
+
+
+# ========== GLOBAL VARIABLES ==========
+#MUSIC_DIR - Directory with music files (either default or specified with $1)
+#NUM_SONGS - number of songs in $MUSIC_DIR
+#MUSIC_LIST - array of songs in $MUSIC_DIR
+#REQUESTED_INDEX - either SHUFFLE or number between 0 - NUM_SONGS, used as parameter for play_song (processed into SONG_INDEX)
+#SONG_INDEX - random or specified number between 0 - NUM_SONGS, used as index to access song file from MUSIC_LIST
+#EXTENSIONS - file extensions *.mp3, *.wav, etc (feel free to modify, preserving current format)
+# ========== /GLOBAL VARIABLES ==========
+
 
 # ========== HELPER FUNCTIONS ==========
 function clearscreen() {
@@ -18,20 +46,22 @@ function clearscreen() {
 }
 
 function ctrl_c() {
-	killall afplay &> /dev/null
+	unbold
+	stop_song
 	clearscreen 
 	exit 0
 }
 
 function pkg_installed() {
 	man "$1" &> /dev/null
-	status=$? #if the man page exists status will be 0, else 1
+	local status=$? #if the man page exists status will be 0, else 1
 	return $status
 }
 
 function is_not_digit() {
+	first_char="${1:0:1}"
 	re='^[0-9]+$'
-	if ! [[ "$1" =~ $re ]] ; then # $1 is not a digit, return error code 0 (sucess)
+	if ! [[ "$1" =~ $re ]] || [ "$first_char" -eq 0 ]; then # $1 is not a digit, return error code 0 (sucess)
    		return 0
    	else
    		return 1 # $1 is a digit, return error code 1 (failure)
@@ -44,24 +74,143 @@ function float_to_int() {
 	echo $var
 }
 
+function bold() {
+	tput bold
+}
+
+function unbold() {
+	tput sgr0
+}
+
+function stop_song() {
+	killall afplay &> /dev/null
+	clearscreen
+}
+
 #Finds number of songs in directory (MUSIC_DIR)
 function num_songs() {
-	echo $(ls -l "$MUSIC_DIR"/*.mp3 *.wav *.m4a *.aif *.flac 2> /dev/null | wc -l)
-    #Note: the command "2> /dev/null" redirects error messages, but leaves regular output
+	echo $(ls -l "$MUSIC_DIR"/$EXTENSIONS 2> /dev/null | wc -l)
+    	#Note: the command "2> /dev/null" redirects error messages, but leaves regular output
+}
+
+function is_invalid() {
+	if is_not_digit "$1" || [ "$1" -gt $NUM_SONGS ] || [ "$1" -lt 0 ]; then
+		return 0
+	fi		
+	return 1
 }
 # ========== /HELPER FUNCTIONS ==========
 
-#Prints formatting, plays random song, defines a global variable with duration of current song
-function play_song() {
-	if [ "$1" = "SHUFFLE" ]; then
-		SONG_INDEX=$(($RANDOM % $NUM_SONGS)) #Get random index in range of NUM_SONGS
-	elif [ "$1" = "PRINT_ASCII" ]; then
-		: #do nothing, this option is just for re-printing the mp3 player ascii art 
-	else
-		SONG_INDEX="$1"
-		REQUESTED_INDEX="SHUFFLE" #resets for next time
+# ========== MAIN FUNCTIONS ==========
+function setup() {
+	trap ctrl_c INT #if the user enters ctrl -c, allow me to do cleanup first
+
+	#If the number of args > 1, exit
+	if [ "$#" -gt 1 ]; then
+		bold; echo "Check your arguments! Only provide an [optional] path to your music directory."; unbold
+		exit 1 
+	#If the number of args = 1, that arg must be a path to your music files
+	elif [ "$#" -eq 1 ]; then
+		#Set MUSIC_DIR to user-specified path to audio files
+		#Allow cd to throw an error if this is an improper path, no big deal
+		MUSIC_DIR="$1"
 	fi
 
+	#Create array of all .mp3 files in MUSIC_DIR
+	cd "$MUSIC_DIR"
+	MUSIC_LIST=( $EXTENSIONS ) #Array of all music files
+
+	#Get the number of songs in the specified directory, make sure it isn't 0
+	NUM_SONGS=$(num_songs)
+	if [ $NUM_SONGS -eq 0 ]; then
+		bold; echo "Found no songs in specified directory!"; unbold
+		exit 1
+	fi
+
+	clearscreen
+}
+
+#List files/indexes for user and allow them to scroll through in less
+function show_songs() {
+	#NF - Last field (File name), NR - Row number, less -S turns off word fold
+	bold; find "$MUSIC_DIR"/$EXTENSIONS 2> /dev/null | awk -F'/' '{print "["NR-1"]\t" $NF}' | less -S; unbold
+}
+
+#Download song, update number of songs, update array of songs
+function download_song() {
+	if pkg_installed "youtube-dl"; then
+		clearscreen
+		bold; read -p "Enter URL: " URL && cd $MUSIC_DIR; echo; unbold
+		youtube-dl --extract-audio --audio-format mp3 --output "%(title)s.%(ext)s" "$URL" && NUM_SONGS=$(num_songs) && MUSIC_LIST=( $EXTENSIONS )
+	
+		local status=$?
+		if [ $status = 0 ]; then
+			bold; echo "Success! Check your $MUSIC_DIR folder for the file."; unbold; read -t 3
+		else
+			echo; bold; read -p "Press any key to continue."; unbold
+		fi
+
+	else
+		bold; echo "You don't have youtube-dl installed. Install using your desired package manager then try again."; unbold; read -t 5
+	fi
+}
+
+function show_pick_song_options() {
+	print_ascii_art
+	bold; echo "(q)uit, (l)ibrary"; unbold
+	bold; printf "|"; unbold; printf "| Play Song #: "
+}
+
+#Sets global var REQUESTED_INDEX to user specified song index
+function pick_song() {
+	local index #used to store potential index for next song
+	stty sane #fixes strange bug with delete key not being picked up
+	show_pick_song_options
+	#printf "%s" "$index"
+
+
+	while :; do
+		#read -n 1 makes keys get read right away
+		local char
+		read -r -n 1 char
+
+		#quit
+	    	if [[ "$char" = "q" ]]; then
+	       		show_music_player && return
+	       	#show songs
+	       	elif [[ "$char" = "l" ]]; then
+			show_songs
+			index=""
+			show_pick_song_options
+		#elif [[ "$char" = "^?" ]]; then
+			#echo "delete pressed"
+		#User pressed enter, assess their index
+		elif [[ "$char" = "" ]]; then
+			if is_invalid "$index"; then
+				bold; echo "Index is invalid."; unbold;
+				index="" #reset index
+				read -t 1
+				show_pick_song_options
+				continue #try again
+			#Index is valid
+			else
+				REQUESTED_INDEX="$index"
+				return
+			fi
+		#User is still typing the index
+	   	else
+	   		index="$index$char" # append input
+	   	fi
+	done
+}
+
+function show_music_player() {
+	print_ascii_art
+	show_options "$INT_DURATION" "1"
+}
+
+function print_ascii_art() {
+	clearscreen
 	#formatting (optimized for 80 by 24 terminal window)
 	tput rmam #disables line wrap
 	echo " _______________________________"
@@ -85,137 +234,84 @@ function play_song() {
 	echo "| |                              |"
 	echo " \|______________________________|"
 	tput smam #re-enables line wrap
+}
 
-	#if we're not just printing the ascii, go on and play the song
-	if [ "$1" != "PRINT_ASCII" ]; then
-		#Duration of current song in seconds (global variable)
-		FLOAT_DURATION=$(afinfo "$MUSIC_DIR"/"${MUSIC_LIST[$SONG_INDEX]}" | awk '/estimated duration/ { print $3 }')
-
-		#Play song file (process runs in the background)
-		afplay "$MUSIC_DIR"/"${MUSIC_LIST[$SONG_INDEX]}" &
+#Prints formatting, plays random song, defines a global variable with duration of current song
+function play_song() {
+	if [ "$1" = "SHUFFLE" ]; then
+		SONG_INDEX=$(($RANDOM % $NUM_SONGS)) #Get random index in range of NUM_SONGS
+	else
+		SONG_INDEX="$1"
+		REQUESTED_INDEX="SHUFFLE" #resets for next time
 	fi
+
+	print_ascii_art
+
+	#Duration of current song in seconds (global variable)
+	FLOAT_DURATION=$(afinfo "$MUSIC_DIR"/"${MUSIC_LIST[$SONG_INDEX]}" | awk '/estimated duration/ { print $3 }')
+
+	#Play song file (process runs in the background)
+	afplay "$MUSIC_DIR"/"${MUSIC_LIST[$SONG_INDEX]}" &
 }
 
 #Prints options, times out after song ends so another one can play
-function give_options() {
+function show_options() {
 	#If no option is provided before the song stops playing, then go to the next song
 	#"TIMEOUT" is a default value; if $OPTION still equals "TIMEOUT" after read, we know the user didn't input anything
-	OPTION="TIMEOUT"
+	local option="TIMEOUT"
 
-	#will be 1 if user attempts to issue invalid command, blank otherwise
-	RETRY=$2
+	echo "(n)ext, (q)uit, (l)ibrary, (p)ick, (d)ownload"
+	
+	#we only want to set seconds to 0 when we start playing a new song ($2 will be "1" if song is already playing)
+	if [ "$2" == "" ]; then
+   		SECONDS=0
+   	fi
 
-	echo "(n)ext, (q)uit, (l)ist songs, (d)ownload"
+	read -n 1 -s -t $(($INT_DURATION - $SECONDS)) option
 
-	#If user entered invalid option, we don't want to reset the read timer
-	if [ RETRY = "1" ]; then
-		read OPTION
-	#This is our first time presenting user with options, set the timer for duration of the song
-	else
-		read -t $INT_DURATION OPTION
-	fi
-
-# =========== OPTIONS ===========
+	# =========== OPTIONS ===========
 	#Next song; OR song duration has expired
-	if [ "$OPTION" = "n" ] || [ "$OPTION" = "TIMEOUT" ]; then
-		killall afplay &> /dev/null
-		clearscreen
-
+	if [ "$option" = "n" ] || [ "$option" = "TIMEOUT" ]; then
+		stop_song
 	#quit
-	elif [ "$OPTION" = "q" ]; then
-		killall afplay &> /dev/null
+	elif [ "$option" = "q" ]; then
+		ctrl_c
+	#list available songs
+	elif [ "$option" = "l" ]; then
+		show_songs
+		show_music_player
+	#ask user to pick a song
+	elif [ "$option" = "p" ]; then
+		pick_song #Sets REQUESTED_INDEX to valid index
+		stop_song
 		clearscreen
-		exit 0
-
-	#list songs to choose from
-	elif [ "$OPTION" = "l" ]; then
-		clearscreen; tput bold
-		echo "=== Note the index of the file you want to play ==="
-		echo "=== Hit [q] when finished browsing === "; echo 
-		echo "=== Hit [ENTER] to continue === "
-		read -t 6; clearscreen
-
-		#List files/indexes for user and allow them to scroll through in less
-		#NF - Last field (File name), NR - Row number, less -S turns off word fold
-		find "$MUSIC_DIR"/*.mp3 | awk -F'/' '{print "["NR-1"]\t" $NF}' | less -S
-		
-		#Read index and make sure it's in range/a digit
-		while read -p "play song #: " REQUESTED_INDEX && is_not_digit "$REQUESTED_INDEX" || [ "$REQUESTED_INDEX" -gt $NUM_SONGS ] || [ "$REQUESTED_INDEX" -lt 0 ]; do
-  			echo "Index is invalid."
-		done
-
-		tput sgr0
-		killall afplay &> /dev/null
-		clearscreen
-
-	elif [ "$OPTION" = "d" ]; then
-		if pkg_installed "youtube-dl"; then
-			clearscreen; tput bold; 
-			read -p "Enter URL: " URL; cd $MUSIC_DIR; tput sgr0
-			youtube-dl --extract-audio --audio-format mp3 --output "%(title)s.%(ext)s" $URL && NUM_SONGS=$(num_songs) #update number of songs
-			tput bold; echo "Success! Check your $MUSIC_DIR folder for the file."; tput sgr0; read -t 2 #keep output on screen for a moment
-			play_song "PRINT_ASCII"
-			give_options "$INT_DURATION" "1" #simply show menu again as if nothing happened
-		else
-			echo "You don't have youtube-dl installed. Install using your desired package manager then try again."
-			clearscreen
-			play_song "PRINT_ASCII"
-			give_options "$INT_DURATION" "1" #simply show menu again as if nothing happened
-		fi
-
+	#download song from url
+	elif [ "$option" = "d" ]; then
+		download_song
+		show_music_player
 	#Invalid input; show options again and do nothing
 	else
-		give_options "$INT_DURATION" "1"
+		show_music_player
 	fi
-# =========== /OPTIONS ===========
+	# =========== /OPTIONS ===========
 }
+# ========== /MAIN FUNCTIONS ==========
+
 
 #The script will start executing here
-
-# ============ SETUP ============ #
-trap ctrl_c INT #if the user enters ctrl -c, allow me to do cleanup first
-
+EXTENSIONS="*.mp3 *.wav *.m4a *.aif *.flac"
 MUSIC_DIR=~/Downloads #default directory of audio files
+setup "$@" #pass arguments to script into function
 
-#If the number of args > 1, exit
-if [ "$#" -gt 1 ]; then
-	tput bold
-	echo "Check your arguments! Only provide an [optional] path to your music directory."
-	tput sgr0
-	exit 1 
-
-#If the number of args = 1, that arg must be the path
-elif [ "$#" -eq 1 ]; then
-	#Set MUSIC_DIR to user-specified path to audio files
-	#Allow cd to throw an error if this is an improper path, no big deal
-	MUSIC_DIR="$1"
-fi
-
-#Create array of all .mp3 files in MUSIC_DIR
-cd "$MUSIC_DIR"
-MUSIC_LIST=( *.mp3 *.wav *.m4a *.aif *.flac ) #Array of all music files
-
-#Get the number of songs in the specified directory, make sure it isn't 0
-NUM_SONGS=$(num_songs)
-if [ $NUM_SONGS -eq 0 ]; then
-	tput bold
-	echo "Found no songs in specified directory!"
-	tput sgr0
-	exit 1
-fi
-
-# ============ MAIN EXECUTION LOOP ============ #
-clearscreen
-
-#Value is changed by give_options when user specifies an index
+#Value is changed by show_options when user specifies an index
 #Value is reset to SHUFFLE by play_song whenever a new song is played
 REQUESTED_INDEX="SHUFFLE" #Begin by shuffling music
 
+# ============ MAIN EXECUTION LOOP ============ #
 while :;
 do	
 	play_song "$REQUESTED_INDEX"
-
-	#Show options for INT_DURATION seconds (entirety of song)
 	INT_DURATION=$(float_to_int "$FLOAT_DURATION")
-	give_options "$INT_DURATION"
+	#Show options for INT_DURATION seconds (entirety of song)
+	show_options "$INT_DURATION"
 done
