Add 'play previous song' functionality

diff --git a/teapot b/teapot
--- a/teapot
+++ b/teapot
@@ -1,5 +1,14 @@
 #!/bin/bash
 
+#to install:
+#1) releases
+#2) wget from website
+#3) wget from github
+#4) download then run make?
+#5) http://kinolien.github.io/gitzip github pages goto zip file
+#https://askubuntu.com/questions/148421/how-to-programmatically-edit-a-file-using-only-terminal
+	#sed to replace MUSIC_DIR=~/Downloads with path
+
 #==== FIXES ====
 #TODO - if possible, pause
 #TODO - make ./config, replace $MUSIC_DIR with user's default for good
@@ -9,6 +18,7 @@
 #TODO - find strange bug with n not working sometimes
 #TODO - catch ctrl z
 #TODO - fix mpg123 weird song start crackle
+#TODO - make sure afinfo, afplay, mpg123, ffmpeg are installed prior to opening
 
 
 #==== FEATURES ====
@@ -27,6 +37,8 @@
 	# eesh, no bloat pls
 #TODO - show metadata option (afinfo, mpg123, ffprobe)
 #TODO - integrate all options from mpg123 into linux version
+#TODO - arrowkeys for next/back
+
 
 
 # ========== GLOBAL VARIABLES ==========
@@ -36,6 +48,7 @@
 #REQUESTED_INDEX - either SHUFFLE or number between 0 - NUM_SONGS, used as parameter for play_song (processed into SONG_INDEX)
 #SONG_INDEX - random or specified number between 0 - NUM_SONGS, used as index to access song file from MUSIC_LIST
 #EXTENSIONS - file extensions *.mp3, *.wav, etc (feel free to modify, preserving current format)
+#HISTORY - array of indeces of all songs played in current session
 # ========== /GLOBAL VARIABLES ==========
 
 
@@ -60,17 +73,18 @@ function pkg_installed() {
 function is_not_digit() {
 	first_char="${1:0:1}"
 	re='^[0-9]+$'
+
 	if ! [[ "$1" =~ $re ]] || [ "$first_char" -eq 0 ]; then # $1 is not a digit, return error code 0 (sucess)
    		return 0
-   	else
-   		return 1 # $1 is a digit, return error code 1 (failure)
-	fi
+   	fi
+
+   	return 1 # $1 is a digit, return error code 1 (failure)
 }
 
 #Ceiling + 1 using bc
 function float_to_int() {
-	var=`echo "$1/1 + 2" | bc`
-	echo $var
+	var=$(echo "$1/1 + 2" | bc)
+	echo "$var"
 }
 
 function bold() {
@@ -88,14 +102,22 @@ function stop_song() {
 
 #Finds number of songs in directory (MUSIC_DIR)
 function num_songs() {
-	echo $(ls -l "$MUSIC_DIR"/$EXTENSIONS 2> /dev/null | wc -l)
-    	#Note: the command "2> /dev/null" redirects error messages, but leaves regular output
+	ls -l "$MUSIC_DIR"/$EXTENSIONS 2> /dev/null | wc -l
+	#Note: the command "2> /dev/null" redirects error messages, but leaves regular output
 }
 
-function is_invalid() {
-	if is_not_digit "$1" || [ "$1" -gt $NUM_SONGS ] || [ "$1" -lt 0 ]; then
+function is_invalid_index() {
+	if is_not_digit "$1" || [ "$1" -gt "$NUM_SONGS" ] || [ "$1" -lt 0 ]; then
 		return 0
 	fi		
+	return 1
+}
+
+function not_replay() {
+	#if this is the first song, or if the current song is already recorded in history
+	if [ "${#HISTORY[@]}" -eq 0 ] || [ "$SONG_INDEX" != "${HISTORY[${#HISTORY[@]}-1]}" ]; then
+		return 0
+	fi
 	return 1
 }
 # ========== /HELPER FUNCTIONS ==========
@@ -111,20 +133,24 @@ function setup() {
 	#If the number of args = 1, that arg must be a path to your music files
 	elif [ "$#" -eq 1 ]; then
 		#Set MUSIC_DIR to user-specified path to audio files
-		#Allow cd to throw an error if this is an improper path, no big deal
 		MUSIC_DIR="$1"
 	fi
 
-	#Create array of all .mp3 files in MUSIC_DIR
-	cd "$MUSIC_DIR"
-	MUSIC_LIST=( $EXTENSIONS ) #Array of all music files
+	#cd throws error and exits if improper path
+	cd "$MUSIC_DIR" || exit
 
 	#Get the number of songs in the specified directory, make sure it isn't 0
 	NUM_SONGS=$(num_songs)
-	if [ $NUM_SONGS -eq 0 ]; then
+	if [ "$NUM_SONGS" -eq 0 ]; then
 		bold; echo "Found no songs in specified directory!"; unbold
 		exit 1
 	fi
+
+	#Create array of all audio files in MUSIC_DIR
+	MUSIC_LIST=( $EXTENSIONS )
+	
+	#Will store all songs which have been played in current session
+	HISTORY=()
 
 	clearscreen
 }
@@ -135,18 +161,25 @@ function show_songs() {
 	bold; find "$MUSIC_DIR"/$EXTENSIONS 2> /dev/null | awk -F'/' '{print "["NR-1"]\t" $NF}' | less -S; unbold
 }
 
+#Set REQUESTED_INDEX to the previous song played
+function queue_previous() {
+	#pop last element of the history array
+	REQUESTED_INDEX="${HISTORY[${#HISTORY[@]}-1]}"
+}
+
 #Download song, update number of songs, update array of songs
 function download_song() {
 	if pkg_installed "youtube-dl"; then
-		clearscreen
-		bold; read -p "Enter URL: " URL && cd $MUSIC_DIR; echo; unbold
+		bold; read -r -p "Enter URL: " URL && cd "$MUSIC_DIR"; unbold
 		youtube-dl --extract-audio --audio-format mp3 --output "%(title)s.%(ext)s" "$URL" && NUM_SONGS=$(num_songs) && MUSIC_LIST=( $EXTENSIONS )
 	
-		local status=$?
+		local status=$? #if song downloaded successfully, status is 0
 		if [ $status = 0 ]; then
 			bold; echo "Success! Check your $MUSIC_DIR folder for the file."; unbold; read -t 3
+			clearscreen
 		else
-			echo; bold; read -p "Press any key to continue."; unbold
+			read -t 3
+			clearscreen
 		fi
 
 	else
@@ -160,13 +193,11 @@ function show_pick_song_options() {
 	bold; printf "|"; unbold; printf "| Play Song #: "
 }
 
-#Sets global var REQUESTED_INDEX to user specified song index
+#Sets REQUESTED_INDEX to user specified song index
 function pick_song() {
 	local index #used to store potential index for next song
 	stty sane #fixes strange bug with delete key not being picked up
 	show_pick_song_options
-	#printf "%s" "$index"
-
 
 	while :; do
 		#read -n 1 makes keys get read right away
@@ -174,24 +205,22 @@ function pick_song() {
 		read -r -n 1 char
 
 		#quit
-	    	if [[ "$char" = "q" ]]; then
+		if [[ "$char" = "q" ]]; then
 	       		show_music_player && return
-	       	#show songs
-	       	elif [[ "$char" = "l" ]]; then
+		#show songs
+		elif [[ "$char" = "l" ]]; then
 			show_songs
 			index=""
 			show_pick_song_options
-		#elif [[ "$char" = "^?" ]]; then
-			#echo "delete pressed"
 		#User pressed enter, assess their index
 		elif [[ "$char" = "" ]]; then
-			if is_invalid "$index"; then
+			if is_invalid_index "$index"; then
 				bold; echo "Index is invalid."; unbold;
 				index="" #reset index
 				read -t 1
 				show_pick_song_options
 				continue #try again
-			#Index is valid
+			#Index is valid, submit it
 			else
 				REQUESTED_INDEX="$index"
 				return
@@ -251,15 +280,20 @@ function play_song() {
 
 	#Play song file (process runs in the background)
 	afplay "$MUSIC_DIR"/"${MUSIC_LIST[$SONG_INDEX]}" &
+
+	#if not replaying last song, add currently playing song to history (at the end of the array)
+	if not_replay; then
+		HISTORY=( "${HISTORY[@]}" "$SONG_INDEX" )
+	fi
 }
 
 #Prints options, times out after song ends so another one can play
 function show_options() {
 	#If no option is provided before the song stops playing, then go to the next song
-	#"TIMEOUT" is a default value; if $OPTION still equals "TIMEOUT" after read, we know the user didn't input anything
+	#"TIMEOUT" is a default value; if $option still equals "TIMEOUT" after read, we know the user didn't input anything
 	local option="TIMEOUT"
 
-	echo "(n)ext, (q)uit, (l)ibrary, (p)ick, (d)ownload"
+	echo "(n)ext, (b)ack, (p)ick, (l)ibrary, (q)uit, (d)ownload"
 	
 	#we only want to set seconds to 0 when we start playing a new song ($2 will be "1" if song is already playing)
 	if [ "$2" == "" ]; then
@@ -272,9 +306,6 @@ function show_options() {
 	#Next song; OR song duration has expired
 	if [ "$option" = "n" ] || [ "$option" = "TIMEOUT" ]; then
 		stop_song
-	#quit
-	elif [ "$option" = "q" ]; then
-		ctrl_c
 	#list available songs
 	elif [ "$option" = "l" ]; then
 		show_songs
@@ -284,6 +315,23 @@ function show_options() {
 		pick_song #Sets REQUESTED_INDEX to valid index
 		stop_song
 		clearscreen
+	#play previous song
+	elif [ "$option" = "b" ]; then
+		#Remove current song from history (unless there's only 1 song in history)
+		if [ "${#HISTORY[@]}" -gt  1 ]; then
+			unset 'HISTORY[${#HISTORY[@]}-1]'
+		fi
+		queue_previous
+		stop_song
+	#FOR DEBUGGING - show history
+	elif [ "$option" = "h" ]; then
+		echo "Length: ${#HISTORY[@]}"
+		printf '%s ' "${HISTORY[@]}"
+		read -t 5
+		show_music_player
+	#quit
+	elif [ "$option" = "q" ]; then
+		ctrl_c
 	#download song from url
 	elif [ "$option" = "d" ]; then
 		download_song
@@ -298,11 +346,11 @@ function show_options() {
 
 
 #The script will start executing here
-EXTENSIONS="*.mp3 *.wav *.m4a *.aif *.flac"
+EXTENSIONS="*.mp3 *.pcm *.wav *.aac *.ogg *.m4a *.aif *.flac"
 MUSIC_DIR=~/Downloads #default directory of audio files
 setup "$@" #pass arguments to script into function
 
-#Value is changed by show_options when user specifies an index
+#Value is changed by show_options, pick_song, or queue_previous
 #Value is reset to SHUFFLE by play_song whenever a new song is played
 REQUESTED_INDEX="SHUFFLE" #Begin by shuffling music
 
